// <auto-generated />
using System;
using MembershipService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MembershipService.API.Migrations
{
    [DbContext(typeof(MembershipDbContext))]
    [Migration("20250724151333_InitialCreate11")]
    partial class InitialCreate11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MembershipService.API.Entities.AccommodationOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NextUServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NextUServiceId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("AccommodationOptions");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasicPlanCategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("BasicPlanTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanLevelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireBooking")
                        .HasColumnType("bit");

                    b.Property<int>("TargetAudienceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VerifyBuy")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanCategoryId");

                    b.HasIndex("BasicPlanTypeId");

                    b.HasIndex("PlanLevelId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TargetAudienceId");

                    b.ToTable("BasicPlans");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlanEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasicPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntitlementRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanId");

                    b.HasIndex("EntitlementRuleId");

                    b.ToTable("BasicPlanEntitlements");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlanRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasicPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationOptionId");

                    b.HasIndex("BasicPlanId");

                    b.ToTable("BasicPlanRooms");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlanType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BasicPlanTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Code = "ACCOMMODATION",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các gói dịch vụ liên quan đến chỗ ở",
                            Name = "Accommodation"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Code = "LIFE_ACTIVITY",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các hoạt động trải nghiệm, xã hội, giải trí",
                            Name = "Life Activity"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.BedTypeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BedTypeOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Queen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "King"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoomInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomInstanceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MembershipService.API.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thủ đô Việt Nam",
                            Name = "Hà Nội"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.ComboPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BasicPlanCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSuggested")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanLevelId")
                        .HasColumnType("int");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetAudienceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VerifyBuy")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanCategoryId");

                    b.HasIndex("PlanLevelId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TargetAudienceId");

                    b.ToTable("ComboPlans");
                });

            modelBuilder.Entity("MembershipService.API.Entities.ComboPlanBasic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasicPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComboPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanId");

                    b.HasIndex("ComboPlanId");

                    b.ToTable("ComboPlanBasics");
                });

            modelBuilder.Entity("MembershipService.API.Entities.ComboPlanDuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasicPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComboPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountDurationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PackageDurationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanId");

                    b.HasIndex("ComboPlanId");

                    b.HasIndex("PackageDurationId");

                    b.ToTable("ComboPlanDurations");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Ecosystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ecosystems");
                });

            modelBuilder.Entity("MembershipService.API.Entities.EntitlementRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("int");

                    b.Property<int?>("LimitPerPeriod")
                        .HasColumnType("int");

                    b.Property<Guid>("NextUServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NextUServiceId");

                    b.ToTable("EntitlementRules");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CityId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CityId1");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CityId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hoàng Cầu"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActorType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MediaGallery");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasicPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComboPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PackageNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanId");

                    b.HasIndex("ComboPlanId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("MembershipService.API.Entities.MembershipHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasicPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComboPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanId");

                    b.HasIndex("ComboPlanId");

                    b.ToTable("MembershipHistory");
                });

            modelBuilder.Entity("MembershipService.API.Entities.NextUService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EcosystemId");

                    b.HasIndex("PropertyId");

                    b.ToTable("NextUServices");
                });

            modelBuilder.Entity("MembershipService.API.Entities.PackageDuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PackageDurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1 tháng",
                            Unit = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "3 tháng",
                            Unit = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "6 tháng",
                            Unit = 2,
                            Value = 6
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BasicPlanTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanTypeId");

                    b.ToTable("PlanCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Áp dụng cho các gói từ 1 tháng trở lên",
                            Name = "Dài hạn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dành cho nhu cầu ngắn ngày hoặc linh hoạt",
                            Name = "Ngắn hạn"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dành riêng cho các gói hoạt động theo sự kiện cụ thể",
                            Name = "Theo sự kiện"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BasicPlanTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicPlanTypeId");

                    b.ToTable("PlanLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cơ bản"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tiêu chuẩn"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cao cấp"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanTargetAudience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanTargetAudiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cá nhân"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nhóm"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Doanh nghiệp"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("LocationId1");

                    b.ToTable("Propertys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực trụ sở chính Hoàng Cầu 1",
                            LocationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Hoàng Cầu Cơ sở 1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực trụ sở chính Hoàng Cầu 2",
                            LocationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Hoàng Cầu Cơ sở 2"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực trụ sở chính Hoàng Cầu 3",
                            LocationId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Hoàng Cầu Cơ sở 3"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomFloorOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomFloorOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "High"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Terrace"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AddOnFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float?>("AreaInSquareMeters")
                        .HasColumnType("real");

                    b.Property<int?>("BedTypeOptionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfBeds")
                        .HasColumnType("int");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomFloorOptionId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomSizeOptionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomViewOptionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationOptionId");

                    b.HasIndex("BedTypeOptionId");

                    b.HasIndex("RoomFloorOptionId");

                    b.HasIndex("RoomSizeOptionId");

                    b.HasIndex("RoomViewOptionId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomSizeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomSizeOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Large"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomViewOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomViewOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sea"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Balcony"
                        });
                });

            modelBuilder.Entity("MembershipService.API.Entities.AccommodationOption", b =>
                {
                    b.HasOne("MembershipService.API.Entities.NextUService", "NextUService")
                        .WithMany("AccommodationOptions")
                        .HasForeignKey("NextUServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.Property", "Property")
                        .WithMany("AccommodationOptions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.RoomType", "RoomType")
                        .WithMany("AccommodationOptions")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NextUService");

                    b.Navigation("Property");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlan", b =>
                {
                    b.HasOne("MembershipService.API.Entities.PlanCategory", "BasicPlanCategory")
                        .WithMany("BasicPlans")
                        .HasForeignKey("BasicPlanCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.BasicPlanType", "BasicPlanType")
                        .WithMany("BasicPlans")
                        .HasForeignKey("BasicPlanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.PlanLevel", "BasicPlanLevel")
                        .WithMany("BasicPlans")
                        .HasForeignKey("PlanLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.Property", "Property")
                        .WithMany("BasicPlans")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.PlanTargetAudience", "PlanTargetAudience")
                        .WithMany("BasicPlans")
                        .HasForeignKey("TargetAudienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BasicPlanCategory");

                    b.Navigation("BasicPlanLevel");

                    b.Navigation("BasicPlanType");

                    b.Navigation("PlanTargetAudience");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlanEntitlement", b =>
                {
                    b.HasOne("MembershipService.API.Entities.BasicPlan", "BasicPlan")
                        .WithMany("BasicPlanEntitlements")
                        .HasForeignKey("BasicPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.EntitlementRule", "EntitlementRule")
                        .WithMany()
                        .HasForeignKey("EntitlementRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicPlan");

                    b.Navigation("EntitlementRule");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlanRoom", b =>
                {
                    b.HasOne("MembershipService.API.Entities.AccommodationOption", "AccommodationOption")
                        .WithMany("BasicPlanRooms")
                        .HasForeignKey("AccommodationOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.BasicPlan", "BasicPlan")
                        .WithMany("BasicPlanRooms")
                        .HasForeignKey("BasicPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccommodationOption");

                    b.Navigation("BasicPlan");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Booking", b =>
                {
                    b.HasOne("MembershipService.API.Entities.RoomInstance", "RoomInstance")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomInstance");
                });

            modelBuilder.Entity("MembershipService.API.Entities.ComboPlan", b =>
                {
                    b.HasOne("MembershipService.API.Entities.PlanCategory", "PlanCategory")
                        .WithMany("ComboPlans")
                        .HasForeignKey("BasicPlanCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.PlanLevel", "PlanLevel")
                        .WithMany("ComboPlans")
                        .HasForeignKey("PlanLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.Property", "Property")
                        .WithMany("ComboPlans")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.PlanTargetAudience", "PlanTargetAudience")
                        .WithMany("ComboPlans")
                        .HasForeignKey("TargetAudienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanCategory");

                    b.Navigation("PlanLevel");

                    b.Navigation("PlanTargetAudience");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MembershipService.API.Entities.ComboPlanBasic", b =>
                {
                    b.HasOne("MembershipService.API.Entities.BasicPlan", "BasicPlan")
                        .WithMany("ComboPlanBasics")
                        .HasForeignKey("BasicPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.ComboPlan", "ComboPlan")
                        .WithMany("ComboPlanBasics")
                        .HasForeignKey("ComboPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BasicPlan");

                    b.Navigation("ComboPlan");
                });

            modelBuilder.Entity("MembershipService.API.Entities.ComboPlanDuration", b =>
                {
                    b.HasOne("MembershipService.API.Entities.BasicPlan", "BasicPlan")
                        .WithMany("ComboPlanDurations")
                        .HasForeignKey("BasicPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.ComboPlan", "ComboPlan")
                        .WithMany("ComboPlanDurations")
                        .HasForeignKey("ComboPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.PackageDuration", "PackageDuration")
                        .WithMany("ComboPlanDurations")
                        .HasForeignKey("PackageDurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BasicPlan");

                    b.Navigation("ComboPlan");

                    b.Navigation("PackageDuration");
                });

            modelBuilder.Entity("MembershipService.API.Entities.EntitlementRule", b =>
                {
                    b.HasOne("MembershipService.API.Entities.NextUService", "NextUService")
                        .WithMany("EntitlementRules")
                        .HasForeignKey("NextUServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NextUService");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Location", b =>
                {
                    b.HasOne("MembershipService.API.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.City", null)
                        .WithMany("Locations")
                        .HasForeignKey("CityId1");

                    b.Navigation("City");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Membership", b =>
                {
                    b.HasOne("MembershipService.API.Entities.BasicPlan", "BasicPlan")
                        .WithMany("Memberships")
                        .HasForeignKey("BasicPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.ComboPlan", "ComboPlan")
                        .WithMany("Memberships")
                        .HasForeignKey("ComboPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BasicPlan");

                    b.Navigation("ComboPlan");
                });

            modelBuilder.Entity("MembershipService.API.Entities.MembershipHistory", b =>
                {
                    b.HasOne("MembershipService.API.Entities.BasicPlan", "BasicPlan")
                        .WithMany("MembershipHistories")
                        .HasForeignKey("BasicPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.ComboPlan", "ComboPlan")
                        .WithMany("MembershipHistories")
                        .HasForeignKey("ComboPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BasicPlan");

                    b.Navigation("ComboPlan");
                });

            modelBuilder.Entity("MembershipService.API.Entities.NextUService", b =>
                {
                    b.HasOne("MembershipService.API.Entities.Ecosystem", "Ecosystem")
                        .WithMany("NextUServices")
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.Property", "Property")
                        .WithMany("NextUServices")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ecosystem");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanCategory", b =>
                {
                    b.HasOne("MembershipService.API.Entities.BasicPlanType", null)
                        .WithMany("BasicPlanCategories")
                        .HasForeignKey("BasicPlanTypeId");
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanLevel", b =>
                {
                    b.HasOne("MembershipService.API.Entities.BasicPlanType", null)
                        .WithMany("BasicPlanLevels")
                        .HasForeignKey("BasicPlanTypeId");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Property", b =>
                {
                    b.HasOne("MembershipService.API.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.Location", null)
                        .WithMany("Properties")
                        .HasForeignKey("LocationId1");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomInstance", b =>
                {
                    b.HasOne("MembershipService.API.Entities.AccommodationOption", "AccommodationOption")
                        .WithMany("Rooms")
                        .HasForeignKey("AccommodationOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MembershipService.API.Entities.BedTypeOption", "BedTypeOption")
                        .WithMany("Rooms")
                        .HasForeignKey("BedTypeOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.RoomFloorOption", "RoomFloorOption")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomFloorOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.RoomSizeOption", "RoomSizeOption")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomSizeOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MembershipService.API.Entities.RoomViewOption", "RoomViewOption")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomViewOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccommodationOption");

                    b.Navigation("BedTypeOption");

                    b.Navigation("RoomFloorOption");

                    b.Navigation("RoomSizeOption");

                    b.Navigation("RoomViewOption");
                });

            modelBuilder.Entity("MembershipService.API.Entities.AccommodationOption", b =>
                {
                    b.Navigation("BasicPlanRooms");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlan", b =>
                {
                    b.Navigation("BasicPlanEntitlements");

                    b.Navigation("BasicPlanRooms");

                    b.Navigation("ComboPlanBasics");

                    b.Navigation("ComboPlanDurations");

                    b.Navigation("MembershipHistories");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BasicPlanType", b =>
                {
                    b.Navigation("BasicPlanCategories");

                    b.Navigation("BasicPlanLevels");

                    b.Navigation("BasicPlans");
                });

            modelBuilder.Entity("MembershipService.API.Entities.BedTypeOption", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MembershipService.API.Entities.City", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MembershipService.API.Entities.ComboPlan", b =>
                {
                    b.Navigation("ComboPlanBasics");

                    b.Navigation("ComboPlanDurations");

                    b.Navigation("MembershipHistories");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Ecosystem", b =>
                {
                    b.Navigation("NextUServices");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Location", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MembershipService.API.Entities.NextUService", b =>
                {
                    b.Navigation("AccommodationOptions");

                    b.Navigation("EntitlementRules");
                });

            modelBuilder.Entity("MembershipService.API.Entities.PackageDuration", b =>
                {
                    b.Navigation("ComboPlanDurations");
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanCategory", b =>
                {
                    b.Navigation("BasicPlans");

                    b.Navigation("ComboPlans");
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanLevel", b =>
                {
                    b.Navigation("BasicPlans");

                    b.Navigation("ComboPlans");
                });

            modelBuilder.Entity("MembershipService.API.Entities.PlanTargetAudience", b =>
                {
                    b.Navigation("BasicPlans");

                    b.Navigation("ComboPlans");
                });

            modelBuilder.Entity("MembershipService.API.Entities.Property", b =>
                {
                    b.Navigation("AccommodationOptions");

                    b.Navigation("BasicPlans");

                    b.Navigation("ComboPlans");

                    b.Navigation("NextUServices");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomFloorOption", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomInstance", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomSizeOption", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomType", b =>
                {
                    b.Navigation("AccommodationOptions");
                });

            modelBuilder.Entity("MembershipService.API.Entities.RoomViewOption", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
